spring:
  application:
    name: IGatewayService
  cloud:
    gateway:
      routes:
        - id: IUserMicroservice
          uri: lb://IUSERMICROSERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - StripPrefix=1
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
        - id: IUserMicroservice
          uri: lb://IUSERMICROSERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
        - id: IUserMicroservice
          uri: lb://IUSERMICROSERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
        - id: IUserMicroservice
          uri: lb://IUSERMICROSERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter # Login, Register 제외한 모든 요청은 토큰이 필요하다.
        - id: ICatalogService
          uri: lb://ICATALOGSERVICE
          predicates:
            - Path=/catalog-service/**
          filters:
            - StripPrefix=1
        - id: IOrderService
          uri: lb://IORDERMICROSERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges

#token:
#  secret: Oh8IUy9dXyn8HfQBKWTPZ6r9GmzODPxHHfEk0lsYiEaS0Q26U1XgJPcAO6pYmgBn
