spring:
  application:
    name: IGatewayService
  cloud:
    gateway:
      routes:
        - id: IUserMicroservice
          uri: lb://IUSERMICROSERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - StripPrefix=1
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - RemoveRequestHeader=Cookie
        - id: IUserMicroservice
          uri: lb://IUSERMICROSERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
        - id: IUserMicroservice
          uri: lb://IUSERMICROSERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
        - id: ICatalogService
          uri: lb://ICATALOGSERVICE
          predicates:
            - Path=/catalog-service/**
          filters:
            - StripPrefix=1
        - id: IOrderService
          uri: lb://IORDERMICROSERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
