spring:
  application:
    name: IGatewayService
  cloud:
    gateway:
      routes:
        - id: IUserMicroservice
          uri: lb://IUSERMICROSERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: ICatalogService
          uri: lb://ICATALOGSERVICE
          predicates:
              - Path=/catalog-service/**
          filters:
              - StripPrefix=1
        - id: IOrderService
          uri: lb://IORDERMICROSERVICE
          predicates:
              - Path=/order-service/**
          filters:
              - StripPrefix=1

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
