server:
  port: 8888

spring:
  application:
    name: IConfigService
  profiles:
    active: native # 자체 서버에서 설정을 읽어오려면 native로 설정 (일반적으로 설정하지 않음)
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        # git:
        #   uri: 완전히 외부에 있는 파일 저장소 (.git 파일이 존재하는 곳)
